# Generated by Django 3.2.9 on 2021-12-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_login_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.FileField(upload_to='img')),
                ('login', models.IntegerField()),
            ],
        ),
    ]
